version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "wednesday"
      time: "21:30"
      timezone: "Europe/Berlin"
    assignees:
      - "simonneutert"

  - package-ecosystem: "bundler"
    directory: "/"
    groups:
      patch-and-minor-dependencies:
        update-types: ["patch", "minor"]
    schedule:
      interval: "monthly"
      day: "wednesday"
      time: "21:30"
      timezone: "Europe/Berlin"
    assignees:
      - "simonneutert"
