version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "21:45"
      timezone: "Europe/Berlin"
    assignees:
      - "simonneutert"

  - package-ecosystem: "bundler"
    directory: "/"
    groups:
      patch-and-minor-dependencies:
        update-types: ["patch", "minor"]
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "21:45"
      timezone: "Europe/Berlin"
    assignees:
      - "simonneutert"
